// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.Azure.Functions")>]
[<assembly: AssemblyProductAttribute("Suave.Azure.Functions")>]
[<assembly: AssemblyDescriptionAttribute("Suave + Azure Functions = Awesomeness")>]
[<assembly: AssemblyVersionAttribute("0.0.6")>]
[<assembly: AssemblyFileVersionAttribute("0.0.6")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Suave.Azure.Functions"
    let [<Literal>] AssemblyProduct = "Suave.Azure.Functions"
    let [<Literal>] AssemblyDescription = "Suave + Azure Functions = Awesomeness"
    let [<Literal>] AssemblyVersion = "0.0.6"
    let [<Literal>] AssemblyFileVersion = "0.0.6"
