// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.Azure.Functions")>]
[<assembly: AssemblyProductAttribute("Suave.Azure.Functions")>]
[<assembly: AssemblyDescriptionAttribute("Suave + Azure Functions = Awesomeness")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] Version = "0.0.1"
    let [<Literal>] InformationalVersion = "0.0.1"
