// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Suave.Azure.Functions")>]
[<assembly: AssemblyProductAttribute("Suave.Azure.Functions")>]
[<assembly: AssemblyDescriptionAttribute("Suave + Azure Functions = Awesomeness")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] Version = "1.0"
    let [<Literal>] InformationalVersion = "1.0"
